name: Build and Package Applications

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-electron:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./electron

      - name: Build CSS
        run: npm run build-css
        working-directory: ./electron

      - name: Build Electron app
        run: npx electron-builder -mwl
        working-directory: ./electron

      - name: Upload Electron Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: electron-dist
          path: electron/dist/

  build-python:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build Python app
        run: pyinstaller --onefile --windowed QuickLauncher.spec
        working-directory: ./python

      - name: Package Installer
        run: "C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe QuickLauncherInstaller.iss"
        working-directory: ./python

      - name: Upload Python Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python-dist
          path: python/dist/
