name: Build and Package Applications

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-electron:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install electron-builder
        run: npm install -g electron-builder
        working-directory: ./electron

      - name: Install dependencies
        run: npm install
        working-directory: ./electron

      - name: Build CSS
        run: npm run build-css
        working-directory: ./electron

      - name: Build Electron app
        run: electron-builder -mwl
        working-directory: ./electron

      - name: Upload Electron Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: electron-dist
          path: electron/dist/